### ISSUE TITLE
Guide on Values in Config File

### ISSUE THREAD

**Issue by TransientThinker** [caioreix/BetterMissions#14]
I've looked everywhere on your mod page on Thunderstore and here on Github and I can't find any guide as to what the values are for in the config file. As in, what does the 2 mean? twice as long as normal for mission duration/risk/loot/etc.? twice as fast? Things like that. Having a guide for that would be super helpful instead of having to figure out the meaning of each value by lengthy trial and error.

**Comment by caioreix** [comment]
Thank you for your feedback! I will try to explain in detail what each value in the configuration file represents, which will help you better understand how to adjust the missions according to your preferences. I know some values are more confusing, but I kept all of them with the same value/modifier logic to avoid many problems. So, in cases where a value is positive, e.g., Success Chance, the modifier of 2 might make the mission more difficult instead of easier. Just keep this in mind, and if you have any doubts about a standard value, you can check the specific settings for each mission.

My recommendation is to use the modifiers only if you want to adjust just the mission duration. In cases of injury chance and success rate, activate the manual settings.

General Mission Settings
[0.🚩 Mission]
These values are general modifiers that affect all missions. They adjust the difficulty and other main parameters.

MissionLengthModifier: Defines the mission duration modifier. The mission duration value is divided by this modifier. For example, if the value is 2, the mission duration will be half the set value. E.g. (7200 / 2 = 3600)
Default value: 2

MissionSuccessRateBonusModifier: Defines the modifier for the mission success rate bonus. The bonus value is divided by this modifier. (-0.2 / 2 = -0.1) will be easier but (0.1 / 2 = 0.1) will be harder
Default value: 1

MissionInjuryChanceModifier: Defines the modifier for the mission injury chance bonus. The injury chance value is divided by this modifier. (0.3 / 2 = 0.15)
Default value: 1

MissionLootFactorModifier: Defines the modifier for the mission loot factor bonus. The loot factor value is divided by this modifier. (0.5 / 2 = 0.25)
Default value: 1

Specific Mission Settings
Each specific mission has its own settings that can be enabled or disabled as needed. Don't forget that if a specific mission setting is enabled, the modifiers will not be applied to it; instead, the defined values will be used.

[1.🚩 Mission-Reckless-1]
EnableReckless1Settings: Enables the specific settings for the Reckless-1 mission.
Default value: false

Reckless1MissionLength: Sets the duration of the Reckless-1 mission in seconds.
Default value: 7200 (2 hours)

Reckless1MissionSuccessRateBonus: Sets the success rate bonus for the Reckless-1 mission.
Default value: -0.2 (decreases the success rate)

Reckless1MissionInjuryChance: Sets the injury chance bonus for the Reckless-1 mission.
Default value: 0.3 (increases the injury chance)

Reckless1MissionLootFactor: Sets the loot factor bonus for the Reckless-1 mission.
Default value: 0.5 (decreases loot)

[2.🚩 Mission-Reckless-2]
EnableReckless2Settings: Enables the specific settings for the Reckless-2 mission.
Default value: false

Reckless2MissionLength: Sets the duration of the Reckless-2 mission in seconds.
Default value: 1440 (24 minutes)

Reckless2MissionSuccessRateBonus: Sets the success rate bonus for the Reckless-2 mission.
Default value: -0.1 (decreases the success rate)

Reckless2MissionInjuryChance: Sets the injury chance bonus for the Reckless-2 mission.
Default value: 0.3 (increases the injury chance)

Reckless2MissionLootFactor: Sets the loot factor bonus for the Reckless-2 mission.
Default value: 0.75 (decreases loot)

[3.🚩 Mission-Normal]
EnableNormal1Settings: Enables the specific settings for the Normal mission.
Default value: false

Normal1MissionLength: Sets the duration of the Normal mission in seconds.
Default value: 28800 (8 hours)

Normal1MissionSuccessRateBonus: Sets the success rate bonus for the Normal mission.
Default value: 0 (no change in success rate)

Normal1MissionInjuryChance: Sets the injury chance bonus for the Normal mission.
Default value: 0.25 (average injury chance)

Normal1MissionLootFactor: Sets the loot factor bonus for the Normal mission.
Default value: 1 (normal loot)

[4.🚩 Mission-Prepared-1]
EnablePrepared1Settings: Enables the specific settings for the Prepared-1 mission.
Default value: false

Prepared1MissionLength: Sets the duration of the Prepared-1 mission in seconds.
Default value: 57600 (16 hours)

Prepared1MissionSuccessRateBonus: Sets the success rate bonus for the Prepared-1 mission.
Default value: 0.1 (increases success rate)

Prepared1MissionInjuryChance: Sets the injury chance bonus for the Prepared-1 mission.
Default value: 0.2 (decreases injury chance)

Prepared1MissionLootFactor: Sets the loot factor bonus for the Prepared-1 mission.
Default value: 1.25 (increases loot)

[5.🚩 Mission-Prepared-2]
EnablePrepared2Settings: Enables the specific settings for the Prepared-2 mission.
Default value: false

Prepared2MissionLength: Sets the duration of the Prepared-2 mission in seconds.
Default value: 82800 (23 hours)

Prepared2MissionSuccessRateBonus: Sets the success rate bonus for the Prepared-2 mission.
Default value: 0.2 (increases success rate)

Prepared2MissionInjuryChance: Sets the injury chance bonus for the Prepared-2 mission.
Default value: 0.2 (decreases injury chance)

Prepared2MissionLootFactor: Sets the loot factor bonus for the Prepared-2 mission.
Default value: 1.5 (increases loot)

I will update the documentation with this information to facilitate the understanding and configuration of the missions. Thank you again for your feedback and patience!
